#!/usr/bin/env bash
###########################################################################
## JobMaster v0.2 by Henrik Bengtsson, 2004.
## 
## Usage: JobMaster [options] [slave options]
## 
## Options:
##  -help        This page.
##  -list        Lists slaves.
##  -slave       Add slave to known slaves. Has to be specified *after*
##               -slaves to be effective if both are given.
##  -slaves      Specify slave hosts. To give several hosts at once, put
##               them within quotation marks seperated by spaces. If not
##               specified, environment variable SLAVES is used. If that
##               is not set, the slaves file is used.
##  -slavesfile  Specify file contain names of slave hosts. Anything on a
##               row following a '#' is a comment and ignored. Default
##               file is ${HOME}/.jobs/SLAVES.
##  -sort        Sort list of slaves before calling.
##  -unique      Make list of slaves unique (include -sort).
## For slave options, see JobSlave --help. 
##
## Logins on each slave and calls JobSlave with given slave options.
## 
## Example:
## Show details for slaves mc01 and mc02:
##  JobMaster -slaves "mc01 mc02" -details
## Start 'date' recording once an hour on the default slave hosts
##  JobMaster -start -interval 60 -script "date > ${HOME}/.date"
## Stop all running processes and remove all scheduled jobs on the slaves
##  JobMaster -stop 
## 
###########################################################################
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Variables
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
jobSlaveOpts=

this=$0
if test ${this} = ""; then
  echo "INTERNAL ERROR: First argument to JobMaster is empty."
fi

slavesfile=${HOME}/.jobs/SLAVES

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Local functions
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
function usage {
#  thisfile=`type -p $0`;
  grep "\#\# " ${this} | head -4 | cut -c4-;
  echo "Please run '`basename ${this}` -help' to see more detailed information."
} 

function help {
#  thisfile=`type -p $0`;
  grep "\#\# " ${this} | cut -c4-;
}

function verbose {
  if test "${verbose}" != "0"; then
    echo "$*"
  fi
}

function error {
  # Hmm, how to write/echo to stderr?!? Found this discussion
  # http://unix.derkeiler.com/Mailing-Lists/AIX-L/2003-08/0190.html
  /usr/bin/env ksh -c "exec 1>&2; echo '$*'"
  exit
}

function debug {
  if test "${debug}" != "0"; then
    # Hmm, how to write/echo to stderr?!? Found this discussion
    # http://unix.derkeiler.com/Mailing-Lists/AIX-L/2003-08/0190.html
    /usr/bin/env ksh -c "exec 1>&2; echo '$*'"
  fi
}

function updateSlaves {
  # Trim value
  SLAVES=`echo ${SLAVES}`
  if test "${SLAVES}" = ""; then
    if test -f "${slavesfile}"; then
      SLAVES=`cut -d# -f1 ${slavesfile}`
    fi
  fi
  # Trim value
  SLAVES=`echo ${SLAVES}`
}

function showSlaves {
  updateSlaves
  echo ${SLAVES}
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Parse arguments
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if test -z "$1"; then
  usage
  exit
fi

while test -n "$1"; do 
  case "$1" in 
    "-help"|"--help")
      help                                     # Calls the help() function
      exit
      ;; 
    "-list")
      showSlaves
      exit
      ;;
    "-slavesfile")
      shift
      # Option overrides previos settings.
      SLAVES=""
      slavesfile="$1"
      updateSlaves
      ;;
    "-slaves")
      shift
      # Option overrides previos settings.
      SLAVES="$1"
      ;;
    "-slave")
      shift
      SLAVES="${SLAVES} $1"
      ;;
    "-sort")
      SLAVES=`for s in ${SLAVES}; do echo ${s}; done | sort`
      ;;
    "-unique")
      SLAVES=`for s in ${SLAVES}; do echo ${s}; done | sort -u`
      ;;
    *)
      jobSlaveOpts="${jobSlaveOpts} $1"
      ;;
  esac 
  shift
done

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Validate arguments
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
updateSlaves

# Assert that slave hosts are given.
if test "${SLAVES}" = ""; then
  error "No slaves specified."
fi

# Trim variable jobSlaveOpts
jobSlaveOpts=`echo ${jobSlaveOpts}`

# Assert that slave options are given.
if test "${jobSlaveOpts}" = ""; then
  error "No options to JobSlave are given. Nothing to do."
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Call each slave
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
echo "Calling slave hosts: ${SLAVES}"
echo "Command: JobSlave ${jobSlaveOpts}"
echo
for slave in ${SLAVES}; do
  echo "Slave ${slave}:"
  ssh ${slave} -C "JobSlave ${jobSlaveOpts}"
  echo
done



###########################################################################
# HISTORY:
# 2004-07-09
# o Created.
###########################################################################
